name: "Unit test in CI"

on:
  pull_request:
    branches: ["master", "development"]
  push:
    branches: ["master", "development"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
      - run: npx jest
