name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
            node-version: 16.x
            
      - name: Install Dependencies
        run: npm i
        
      - name: run unit test
        run: npm run test